create table coffee (
	id bigint generated by default as identity,
    name varchar(255),
    price integer,
    primary key (id)
);

INSERT
INTO
	coffee
    (id, name, price)
VALUES
	(1, '아메리카노', 4100);

INSERT
INTO
	coffee
    (id, name, price)
VALUES
	(2, '라뗴', 4600),
    (3, '모카', 5100),
    (4, '오늘의 커피', 3800);

SELECT * FROM COFFEE;

SELECT
	id, name, price
FROM
	coffee
WHERE
	id = 3;

UPDATE
	coffee
SET
	price = 9900
WHERE
	id = 4;

DELETE
FROM
	coffee
WHERE
	id = 4;
